export const products = [
  // الخزف والفخار
  {
    id: 1,
    name: "وعاء خزفي مزخرف",
    description: "وعاء فخاري مصنوع يدوياً بتصميم فيكتوري كلاسيكي، مثالي لتقديم الطعام أو كعنصر ديكور",
    price: 250,
    category: "خزف",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.8,
    reviews: 24,
    inStock: true,
    featured: true,
    materials: ["طين طبيعي", "طلاء خزفي"],
    dimensions: "15 × 15 × 8 سم",
    weight: "0.8 كجم"
  },
  {
    id: 2,
    name: "مزهرية خزفية كلاسيكية",
    description: "مزهرية خزفية مصنوعة يدوياً بتصميم فيكتوري رائع، تضيف لمسة أناقة لأي غرفة",
    price: 280,
    category: "خزف",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.9,
    reviews: 31,
    inStock: true,
    featured: true,
    materials: ["طين عالي الجودة", "طلاء مقاوم"],
    dimensions: "20 × 12 × 25 سم",
    weight: "1.2 كجم"
  },
  {
    id: 3,
    name: "طقم أواني خزفية",
    description: "طقم من 6 أواني خزفية مصنوعة يدوياً، مثالية للعائلة",
    price: 450,
    category: "خزف",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.7,
    reviews: 18,
    inStock: true,
    featured: false,
    materials: ["طين طبيعي", "طلاء آمن للطعام"],
    dimensions: "متعدد الأحجام",
    weight: "3.5 كجم"
  },

  // النسيج والتطريز
  {
    id: 4,
    name: "وسادة مطرزة باليد",
    description: "وسادة فاخرة مطرزة بتصاميم عربية تقليدية، تضيف راحة وأناقة للجلوس",
    price: 180,
    category: "نسيج",
    image: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400",
    rating: 4.6,
    reviews: 42,
    inStock: true,
    featured: true,
    materials: ["قطن 100%", "حرير طبيعي"],
    dimensions: "45 × 45 سم",
    weight: "0.3 كجم"
  },
  {
    id: 5,
    name: "سجادة منسوجة يدوياً",
    description: "سجادة فاخرة منسوجة باليد بتصميم عربي أصيل، تجمع بين الجمال والراحة",
    price: 450,
    category: "نسيج",
    image: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400",
    rating: 4.9,
    reviews: 28,
    inStock: true,
    featured: true,
    materials: ["صوف طبيعي", "قطن مصري"],
    dimensions: "120 × 180 سم",
    weight: "4.2 كجم"
  },
  {
    id: 6,
    name: "مفرش طاولة مطرز",
    description: "مفرش طاولة مطرز يدوياً بتصاميم فيكتورية أنيقة",
    price: 320,
    category: "نسيج",
    image: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400",
    rating: 4.5,
    reviews: 15,
    inStock: true,
    featured: false,
    materials: ["كتان طبيعي", "حرير"],
    dimensions: "150 × 150 سم",
    weight: "0.8 كجم"
  },
  {
    id: 7,
    name: "ستارة مطرزة كلاسيكية",
    description: "ستارة مطرزة يدوياً بتصميم فيكتوري فاخر",
    price: 580,
    category: "نسيج",
    image: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400",
    rating: 4.8,
    reviews: 22,
    inStock: true,
    featured: false,
    materials: ["حرير طبيعي", "دانتيل"],
    dimensions: "250 × 150 سم",
    weight: "1.5 كجم"
  },

  // الخشب والمنحوتات
  {
    id: 8,
    name: "صندوق خشبي منحوت",
    description: "صندوق خشبي منحوت يدوياً بتصميم فيكتوري أنيق، مثالي لحفظ المجوهرات",
    price: 320,
    category: "خشب",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    rating: 4.7,
    reviews: 35,
    inStock: true,
    featured: true,
    materials: ["خشب زان", "برونز"],
    dimensions: "25 × 15 × 10 سم",
    weight: "1.8 كجم"
  },
  {
    id: 9,
    name: "إطار مرآة خشبي منحوت",
    description: "إطار مرآة خشبي منحوت يدوياً بتصميم فيكتوري فاخر",
    price: 420,
    category: "خشب",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    rating: 4.8,
    reviews: 19,
    inStock: true,
    featured: false,
    materials: ["خشب ماهوجني", "زجاج"],
    dimensions: "60 × 80 سم",
    weight: "3.2 كجم"
  },
  {
    id: 10,
    name: "طاولة جانبية منحوتة",
    description: "طاولة جانبية خشبية منحوتة يدوياً بتصميم كلاسيكي",
    price: 850,
    category: "خشب",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    rating: 4.9,
    reviews: 12,
    inStock: true,
    featured: false,
    materials: ["خشب بلوط", "برونز"],
    dimensions: "45 × 45 × 60 سم",
    weight: "8.5 كجم"
  },
  {
    id: 11,
    name: "كرسي خشبي منحوت",
    description: "كرسي خشبي منحوت يدوياً بتصميم فيكتوري أنيق",
    price: 1200,
    category: "خشب",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    rating: 4.6,
    reviews: 8,
    inStock: true,
    featured: false,
    materials: ["خشب زان", "قماش فاخر"],
    dimensions: "50 × 60 × 90 سم",
    weight: "12 كجم"
  },

  // الجلود والحقائب
  {
    id: 12,
    name: "حقيبة جلدية يدوية",
    description: "حقيبة جلدية مصنوعة يدوياً بتصميم كلاسيكي أنيق",
    price: 380,
    category: "جلد",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
    rating: 4.7,
    reviews: 45,
    inStock: true,
    featured: true,
    materials: ["جلد طبيعي", "برونز"],
    dimensions: "30 × 25 × 10 سم",
    weight: "0.9 كجم"
  },
  {
    id: 13,
    name: "محفظة جلدية منحوتة",
    description: "محفظة جلدية منحوتة يدوياً بتصاميم عربية تقليدية",
    price: 220,
    category: "جلد",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
    rating: 4.5,
    reviews: 38,
    inStock: true,
    featured: false,
    materials: ["جلد طبيعي", "خيوط قطنية"],
    dimensions: "12 × 9 × 2 سم",
    weight: "0.2 كجم"
  },
  {
    id: 14,
    name: "حزام جلد منحوت",
    description: "حزام جلد منحوت يدوياً بتصميم فيكتوري أنيق",
    price: 180,
    category: "جلد",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
    rating: 4.4,
    reviews: 26,
    inStock: true,
    featured: false,
    materials: ["جلد طبيعي", "برونز"],
    dimensions: "110 × 4 سم",
    weight: "0.3 كجم"
  },

  // المعادن والمجوهرات
  {
    id: 15,
    name: "شمعدان نحاسي منحوت",
    description: "شمعدان نحاسي منحوت يدوياً بتصميم فيكتوري فاخر",
    price: 350,
    category: "معادن",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.8,
    reviews: 33,
    inStock: true,
    featured: true,
    materials: ["نحاس أصفر", "فضة"],
    dimensions: "15 × 15 × 25 سم",
    weight: "1.5 كجم"
  },
  {
    id: 16,
    name: "إبريق شاي فضي منحوت",
    description: "إبريق شاي فضي منحوت يدوياً بتصميم كلاسيكي أنيق",
    price: 680,
    category: "معادن",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.9,
    reviews: 17,
    inStock: true,
    featured: false,
    materials: ["فضة 925", "خشب"],
    dimensions: "20 × 15 × 18 سم",
    weight: "2.1 كجم"
  },
  {
    id: 17,
    name: "طقم ملاعق فضية منحوتة",
    description: "طقم من 6 ملاعق فضية منحوتة يدوياً بتصميم فيكتوري",
    price: 420,
    category: "معادن",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.6,
    reviews: 29,
    inStock: true,
    featured: false,
    materials: ["فضة 925"],
    dimensions: "20 سم لكل ملعقة",
    weight: "0.8 كجم"
  },

  // الزجاج والكريستال
  {
    id: 18,
    name: "مزهرية زجاجية منفوخة",
    description: "مزهرية زجاجية منفوخة يدوياً بتصميم فيكتوري رائع",
    price: 280,
    category: "زجاج",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.7,
    reviews: 41,
    inStock: true,
    featured: true,
    materials: ["زجاج كريستال", "ذهب"],
    dimensions: "18 × 18 × 30 سم",
    weight: "1.2 كجم"
  },
  {
    id: 19,
    name: "طقم كؤوس كريستال",
    description: "طقم من 6 كؤوس كريستال منحوتة يدوياً",
    price: 520,
    category: "زجاج",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.8,
    reviews: 23,
    inStock: true,
    featured: false,
    materials: ["كريستال بوهيمي"],
    dimensions: "12 × 12 × 18 سم لكل كأس",
    weight: "2.5 كجم"
  },

  // الإضاءة والشمعدانات
  {
    id: 20,
    name: "مصباح طاولة فيكتوري",
    description: "مصباح طاولة فيكتوري مصنوع يدوياً من النحاس والزجاج",
    price: 450,
    category: "إضاءة",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.9,
    reviews: 31,
    inStock: true,
    featured: true,
    materials: ["نحاس", "زجاج", "حرير"],
    dimensions: "25 × 25 × 45 سم",
    weight: "2.8 كجم"
  },
  {
    id: 21,
    name: "شمعدان برونزي منحوت",
    description: "شمعدان برونزي منحوت يدوياً بتصميم فيكتوري فاخر",
    price: 320,
    category: "إضاءة",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.6,
    reviews: 27,
    inStock: true,
    featured: false,
    materials: ["برونز", "رخام"],
    dimensions: "20 × 20 × 35 سم",
    weight: "3.2 كجم"
  },

  // الديكور والتحف
  {
    id: 22,
    name: "ساعة حائط فيكتورية",
    description: "ساعة حائط فيكتورية مصنوعة يدوياً من الخشب والنحاس",
    price: 780,
    category: "ديكور",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.8,
    reviews: 19,
    inStock: true,
    featured: true,
    materials: ["خشب زان", "نحاس", "زجاج"],
    dimensions: "40 × 40 × 15 سم",
    weight: "4.5 كجم"
  },
  {
    id: 23,
    name: "مرآة إطار خشبي منحوت",
    description: "مرآة بإطار خشبي منحوت يدوياً بتصميم فيكتوري أنيق",
    price: 650,
    category: "ديكور",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.7,
    reviews: 25,
    inStock: true,
    featured: false,
    materials: ["خشب ماهوجني", "زجاج", "برونز"],
    dimensions: "80 × 100 × 8 سم",
    weight: "6.8 كجم"
  },
  {
    id: 24,
    name: "تمثال برونزي كلاسيكي",
    description: "تمثال برونزي منحوت يدوياً بتصميم كلاسيكي فيكتوري",
    price: 1200,
    category: "ديكور",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    rating: 4.9,
    reviews: 14,
    inStock: true,
    featured: false,
    materials: ["برونز", "رخام"],
    dimensions: "25 × 15 × 40 سم",
    weight: "8.2 كجم"
  }
];

export const categories = [
  { id: "all", name: "جميع المنتجات", icon: "fas fa-gem" },
  { id: "خزف", name: "الخزف والفخار", icon: "fas fa-mug-hot" },
  { id: "نسيج", name: "النسيج والتطريز", icon: "fas fa-scroll" },
  { id: "خشب", name: "الخشب والمنحوتات", icon: "fas fa-tree" },
  { id: "جلد", name: "الجلود والحقائب", icon: "fas fa-briefcase" },
  { id: "معادن", name: "المعادن والمجوهرات", icon: "fas fa-gem" },
  { id: "زجاج", name: "الزجاج والكريستال", icon: "fas fa-wine-glass" },
  { id: "إضاءة", name: "الإضاءة والشمعدانات", icon: "fas fa-lightbulb" },
  { id: "ديكور", name: "الديكور والتحف", icon: "fas fa-home" }
]; 